### @name="Cache Product GET"
GET http://localhost:8080/api/products/cache/5
Accept: application/json




### @name="ETAG"
### @name="get product by ID"
GET http://localhost:8080/api/products/etag/2
Accept: application/json

### @name="ETAG"
### @name="get product by ID If-None-Match"
GET http://localhost:8080/api/products/etag/2
Accept: application/json
If-None-Match: "-1496669395"

### @name="get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="get product by ID"
GET http://localhost:8080/api/products/288
Accept: application/json

### @name="add product"
POST http://localhost:8080/api/products
Accept: application/json
Accept-Language: hi
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQHZpc2EuY29tIiwiaWF0IjoxNzI4MzY0ODMxLCJleHAiOjE3MjgzNjYyNzEsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpc3MiOiJodHRwczovL2F1dHNlcnZlci52aXNhLGNvbiJ9.rEoca7UVgfiesW4FGeqN2hmAvqUZ9kXiNsd6rh41Lmc


{
  "name" : "Some Prod",
  "price": 700.00,
  "quantity": 33
}


### @name="update product"
PATCH http://localhost:8080/api/products/2
Accept: application/json
Content-Type: application/json

{
  "price": 259990.00
}