### @name="Cache Product GET"
GET http://localhost:8080/api/products/cache/5
Accept: application/json




### @name="ETAG"
### @name="get product by ID"
GET http://localhost:8080/api/products/etag/2
Accept: application/json

### @name="ETAG"
### @name="get product by ID If-None-Match"
GET http://localhost:8080/api/products/etag/2
Accept: application/json
If-None-Match: "-1496669395"

### @name="get all products"
GET http://localhost:8080/api/products
Accept: application/json

### @name="get product by ID"
GET http://localhost:8080/api/products/288
Accept: application/json

### @name="add product"
POST http://localhost:8080/api/products
Accept: application/json
Accept-Language: hi
Content-Type: application/json


{
  "price": -100.00,
  "quantity": -33
}


### @name="update product"
PATCH http://localhost:8080/api/products/2
Accept: application/json
Content-Type: application/json

{
  "price": 259990.00
}