### @name ="Register User"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "peter@visa.com",
  "password": "secret",
  "username": "Peter",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  }]
}

### @name ="Register Admin"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret",
  "username": "Anna",
  "roles": [ {
  "name": "ROLE_USER",
  "description": "Has basic rights"
},
    {
      "name": "ROLE_ADMIN",
      "description": "Admin rights"
    }]
}


### @name ="Admin Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret"
}


### @name="access Protected Resource"

GET http://localhost:8080/api/orders
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQHZpc2EuY29tIiwiaWF0IjoxNzI4MzYyMDQxLCJleHAiOjE3MjgzNjM0ODEsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cHM6Ly9hdXRzZXJ2ZXIudmlzYSxjb24ifQ.WSvdFUQvl5iBhQUf5DyO9JyXx5QsXTaiLR_ieT5OQEM