### @name ="Register User"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "peter@visa.com",
  "password": "secret",
  "username": "Peter",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  }]
}

### @name ="Register Admin"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret",
  "username": "Anna",
  "roles": [ {
  "name": "ROLE_USER",
  "description": "Has basic rights"
},
    {
      "name": "ROLE_ADMIN",
      "description": "Admin rights"
    }]
}


### @name ="Admin Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret"
}


### @name="access Protected Resource"

GET http://localhost:8080/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQHZpc2EuY29tIiwiaWF0IjoxNzI4MzY0ODMxLCJleHAiOjE3MjgzNjYyNzEsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJpc3MiOiJodHRwczovL2F1dHNlcnZlci52aXNhLGNvbiJ9.rEoca7UVgfiesW4FGeqN2hmAvqUZ9kXiNsd6rh41Lmc
